#!/bin/sh
# $Id: calendar3-stdout 1469 2006-10-23 20:59:34Z stsp $
: ${DIALOG=dialog}

USERDATE=`$DIALOG --extra-button --extra-label "Hold" --help-button --stdout --title "CALENDAR" --calendar "Please choose a date..." 0 0 7 7 1981`

case $? in
  0)
    echo "Date entered: $USERDATE.";;
  1)
    echo "Cancel pressed.";;
  2)
    echo "Help pressed.";;
  3)
    echo "Hold pressed.";;
  255)
    echo "Box closed.";;
esac
