#!/bin/sh
# $Id: pause 1469 2006-10-23 20:59:34Z stsp $
: ${DIALOG=dialog}

$DIALOG --title "PAUSE" --pause "Hi, this is a pause widget" 20 70 10

retval=$?

case $retval in
  0)
    echo "Timeout expired.";;
  1)
    echo "Cancel pressed.";;
  *)
    echo "Unexpected return code: $retval";;
esac
