#!/bin/sh
# $Id: progress 1469 2006-10-23 20:59:34Z stsp $
: ${DIALOG=dialog}

tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

ls -1 >$tempfile
(
while true
do
read text
test -z "$text" && break
ls -ld "$text"
sleep 1
done <$tempfile
) |

$DIALOG --title "PROGRESS" --progressbox 20 70
