#!/bin/sh
# $Id: timebox2-stdout 1469 2006-10-23 20:59:34Z stsp $
: ${DIALOG=dialog}

USERTIME=`$DIALOG --stdout --title "TIMEBOX" --timebox "Please set the time..." 0 0`

case $? in
  0)
    echo "Time entered: $USERTIME.";;
  1)
    echo "Cancel pressed.";;
  255)
    echo "Box closed.";;
esac
